---
- name: Instalar Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Publicar pagina inicial
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: "0644"
  notify: Reiniciar Nginx

- name: Garantir que o Nginx esteja habilitado e ativo
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
